/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface PkImageUploader {
    'image': string;
    'label': string;
    'maxFileSize': number;
    'maxImageHeight': number;
    'maxImageWidth': number;
    'minImageHeight': number;
    'minImageWidth': number;
  }
}

declare global {


  interface HTMLPkImageUploaderElement extends Components.PkImageUploader, HTMLStencilElement {}
  var HTMLPkImageUploaderElement: {
    prototype: HTMLPkImageUploaderElement;
    new (): HTMLPkImageUploaderElement;
  };
  interface HTMLElementTagNameMap {
    'pk-image-uploader': HTMLPkImageUploaderElement;
  }
}

declare namespace LocalJSX {
  interface PkImageUploader {
    'image'?: string;
    'label'?: string;
    'maxFileSize'?: number;
    'maxImageHeight'?: number;
    'maxImageWidth'?: number;
    'minImageHeight'?: number;
    'minImageWidth'?: number;
    'onImagechange'?: (event: CustomEvent<any>) => void;
  }

  interface IntrinsicElements {
    'pk-image-uploader': PkImageUploader;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'pk-image-uploader': LocalJSX.PkImageUploader & JSXBase.HTMLAttributes<HTMLPkImageUploaderElement>;
    }
  }
}


